-- Files required by the CC: Tweaked facility security system updater.
-- The updater fetches this file first, then downloads each listed file from baseUrl.

return {
  appName = "facility_security_system",
  baseUrl = "https://raw.githubusercontent.com/Mauppi/computercraft/master/",
  entry = "security_system.lua",
  serverConfig = {
    path = "security_config.lua",
    target = "security_config.lua",
    required = false,
    minSize = 500,
    contains = {
      "return {",
      "mode = \"server\"",
    },
  },

  assets = {
    { path = "announcements/announcement_jingle.wav", binary = true, kind = "wav" },
    { path = "announcements/jingle_alarm.wav", binary = true, kind = "wav" },
    { path = "announcements/jingle_notification.wav", binary = true, kind = "wav" },
    { path = "announcements/red_alert.wav", binary = true, kind = "wav" },
    { path = "announcements/red_alert_a.wav", binary = true, kind = "wav" },
    { path = "announcements/red_alert_b.wav", binary = true, kind = "wav" },
    { path = "announcements/slopday.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdayanimals.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdaycancelled.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdaygoon.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdaynonono.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdayslop.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdaysloppingit.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdaySuS.wav", binary = true, kind = "wav" },
    { path = "announcements/slopdaywebsite.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_admin.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_alarm.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_attention.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_disengaged.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_doctor.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_employee.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_engaged.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_engineer.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_for.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_lockdown.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_maintenance.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_meeting.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_memeorpo.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_person_crafthessu.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_person_faceremover.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_person_lucsaani.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_person_mauppi.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_person_skaahejo.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_personnelrequest_general_reason.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_place_frontentrance.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_place_mainshaft.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_place_serverroom.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_questioning.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_secalarm.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_security.wav", binary = true, kind = "wav" },
    { path = "announcements/vo_yourequested.wav", binary = true, kind = "wav" },
  },

  files = {
    {
      path = "security_system_defaults.lua",
      required = true,
      minSize = 2000,
      contains = {
        "Default configuration",
        "return {",
        "alarm = {",
      },
    },
    {
      path = "security_system_rednet.lua",
      required = true,
      minSize = 2000,
      contains = {
        "Rednet message wrapping",
        "__securitySystem",
        "function M.wrap",
      },
    },
    {
      path = "aukit.lua",
      required = true,
      minSize = 100000,
      contains = {
        "AUKit",
        "function aukit.play",
        "function aukit.wav",
        "function aukit.stream.wav",
      },
    },
    {
      path = "auplay.lua",
      required = false,
      minSize = 500,
      contains = {
        "local aukit = require \"aukit\"",
        "aukit.play",
      },
    },
    {
      path = "austream.lua",
      required = false,
      minSize = 1000,
      contains = {
        "local aukit = require \"aukit\"",
        "aukit.stream.wav",
        "rednet://",
      },
    },
    {
      path = "security_system_audio.lua",
      required = true,
      minSize = 1000,
      contains = {
        "AUKit-backed audio helpers",
        "function M.loadWav",
        "function M.preparePlaybackPcm",
        "function M.aukitPcmRange",
        "function M.playPcmRange",
        "function M.packPcmSamples",
      },
    },
    {
      path = "security_system_notifications.lua",
      required = true,
      minSize = 1000,
      contains = {
        "Kiosk notification",
        "security_system_announcements",
        "security_system_audio",
        "function M.push",
        "function M.playSound",
        "function M.wavKindAllowed",
      },
    },
    {
      path = "security_system_announcements.lua",
      required = true,
      minSize = 1000,
      contains = {
        "Facility announcement audio",
        "security_system_audio",
        "SECURITY_SYSTEM_ASSET_ROOT",
        "function M.loadWav",
        "function M.buildVoiceBuffer",
        "function M.buildAnnouncementBuffer",
        "playPcmOnSpeakers",
        "mixSamplesAt",
        "scaledSamples",
        "hasSamples",
        "variations",
        "voiceLines",
        "syntheticVoice",
        "speaker_audio_empty",
        "function M.play",
      },
    },
    {
      path = "security_system_app.lua",
      required = true,
      minSize = 2000,
      contains = {
        "CC: Tweaked security system",
        "security_system_defaults",
        "security_system_rednet",
        "security_system_notifications",
        "security_system_announcements",
        "security_system_audio",
        "DEFAULT_CONFIG_URL",
        "installRemoteConfigIfMissing",
        "installKioskConfigIfMissing",
        "function controllerMain()",
        "kiosk_setup",
        "kiosk_badge_login",
        "controller_credential",
        "wrapEndpointPeripheral",
        "pulseSeconds",
        "setAnalogueOutput",
        "readerKindFor",
        "printReaderSourceHints",
        "kioskSetupReaderHints",
        "kioskLocalControllerLoop",
        "kiosk.controller",
        "remove_door",
        "playAlarmAudioSound",
        "alarmAudioStreamLoop",
        "speaker_audio_empty",
        "alarmSyncLeadMillis",
        "soundStartAt",
        "serverTimeMillis",
        "serverMillisToLocalMillis",
        "ensureNotificationPlaybackSchedule",
        "alignAnnouncementPcmToSchedule",
        "alignAlarmPcmToSchedule",
        "doorAnnouncementFields",
        "configuredEventAnnouncement",
        "personnel_request",
        "personnelRequestFields",
        "personnelReasonFields",
        "personnelTitleLabel",
        "kioskLocationArea",
        "kioskPaRequest",
        "configuredAnnouncement",
        "configuredAnnouncementHasAudio",
        "voiceLines",
        "alarmAnnouncementSuppressionActive",
        "announcementCanPlayDuringAlarm",
        "prebufferSeconds",
        "idleWatchdogSeconds",
        "audioWatchdogDelaySeconds",
        "invalidateMonitorCache",
        "broadcastActionAnnouncement",
        "notificationUsesAnnouncementAudio",
        "announcementIsAlarmLike",
        "playFacilityAnnouncement",
        "pruneAnnouncementAudioStreams",
        "feedAnnouncementAudioStreams",
        "handleAnnouncementSpeakerAudioEmpty",
        "includeAlarm",
        "function main()",
        "return {",
      },
    },
    {
      path = "security_system.lua",
      required = true,
      minSize = 300,
      contains = {
        "security_system_app",
        "security_system_audio",
        "AUKIT_MODULE",
        "SECURITY_SYSTEM_ASSET_ROOT",
        "app.run",
      },
    },
    {
      path = "security_system_manifest.lua",
      required = true,
      minSize = 300,
      contains = "security_system_app.lua",
    },
    {
      path = "startup_auto_update.lua",
      required = false,
      minSize = 1000,
      contains = {
        "security_system_manifest.lua",
        "INSTALL_SUBDIR",
        "selectInstallRoot",
        "modeOverride",
        "SELF_UPDATE_FILE",
        "selfUpdateFromGithub",
        "security_local_data.lua",
        "applyLocalDataToConfig",
        "localDataForMode",
        "localDataSummary",
        "locationArea",
        "protectedLocalStatePath",
        "configEntryForMode",
        "overwriteConfigFromGithub",
        "serverConfig",
        "security_kiosk_config.example.lua",
      },
    },
    {
      path = "startup_kiosk.lua",
      required = false,
      minSize = 500,
      contains = "SECURITY_PROGRAM",
    },
    {
      path = "security_config.example.lua",
      required = false,
      minSize = 500,
      contains = "North Ridge Facility",
    },
    {
      path = "security_kiosk_config.example.lua",
      required = false,
      minSize = 300,
      contains = "mode = \"kiosk\"",
    },
    {
      path = "SECURITY_SYSTEM.md",
      required = false,
      minSize = 500,
      contains = "Facility Security System",
    },
  },
}
